# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PipeNetwork_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1968, 836)
        Form.setMouseTracking(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grp_PipeNetworkBuilder = QtWidgets.QGroupBox(Form)
        self.grp_PipeNetworkBuilder.setMouseTracking(True)
        self.grp_PipeNetworkBuilder.setObjectName("grp_PipeNetworkBuilder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.grp_PipeNetworkBuilder)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grp_PipeAndNodeCreation = QtWidgets.QGroupBox(self.grp_PipeNetworkBuilder)
        self.grp_PipeAndNodeCreation.setMouseTracking(True)
        self.grp_PipeAndNodeCreation.setObjectName("grp_PipeAndNodeCreation")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_PipeAndNodeCreation)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_EndNodeName_2 = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        self.lbl_EndNodeName_2.setObjectName("lbl_EndNodeName_2")
        self.gridLayout.addWidget(self.lbl_EndNodeName_2, 4, 0, 1, 1)
        self.tree_Nodes = QtWidgets.QTreeWidget(self.grp_PipeAndNodeCreation)
        self.tree_Nodes.setMouseTracking(True)
        self.tree_Nodes.setObjectName("tree_Nodes")
        self.gridLayout.addWidget(self.tree_Nodes, 12, 2, 1, 1)
        self.lbl_EndNodeName = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        self.lbl_EndNodeName.setObjectName("lbl_EndNodeName")
        self.gridLayout.addWidget(self.lbl_EndNodeName, 3, 0, 1, 1)
        self.le_StartNode = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_StartNode.sizePolicy().hasHeightForWidth())
        self.le_StartNode.setSizePolicy(sizePolicy)
        self.le_StartNode.setMinimumSize(QtCore.QSize(100, 0))
        self.le_StartNode.setObjectName("le_StartNode")
        self.gridLayout.addWidget(self.le_StartNode, 2, 1, 1, 1)
        self.btn_DeletePipe = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        self.btn_DeletePipe.setObjectName("btn_DeletePipe")
        self.gridLayout.addWidget(self.btn_DeletePipe, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 3, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 1, 3, 1)
        self.btn_AddPipe = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        self.btn_AddPipe.setObjectName("btn_AddPipe")
        self.gridLayout.addWidget(self.btn_AddPipe, 7, 1, 1, 1)
        self.lbl_EndNodeName_4 = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        self.lbl_EndNodeName_4.setObjectName("lbl_EndNodeName_4")
        self.gridLayout.addWidget(self.lbl_EndNodeName_4, 6, 0, 1, 1)
        self.le_PipeLength = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_PipeLength.sizePolicy().hasHeightForWidth())
        self.le_PipeLength.setSizePolicy(sizePolicy)
        self.le_PipeLength.setMinimumSize(QtCore.QSize(100, 0))
        self.le_PipeLength.setObjectName("le_PipeLength")
        self.gridLayout.addWidget(self.le_PipeLength, 4, 1, 1, 1)
        self.le_Roughness = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Roughness.sizePolicy().hasHeightForWidth())
        self.le_Roughness.setSizePolicy(sizePolicy)
        self.le_Roughness.setMinimumSize(QtCore.QSize(100, 0))
        self.le_Roughness.setObjectName("le_Roughness")
        self.gridLayout.addWidget(self.le_Roughness, 6, 1, 1, 1)
        self.lbl_EndNodeName_3 = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        self.lbl_EndNodeName_3.setObjectName("lbl_EndNodeName_3")
        self.gridLayout.addWidget(self.lbl_EndNodeName_3, 5, 0, 1, 1)
        self.lbl_StartNode = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        self.lbl_StartNode.setObjectName("lbl_StartNode")
        self.gridLayout.addWidget(self.lbl_StartNode, 2, 0, 1, 1)
        self.le_Diam = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Diam.sizePolicy().hasHeightForWidth())
        self.le_Diam.setSizePolicy(sizePolicy)
        self.le_Diam.setMinimumSize(QtCore.QSize(100, 0))
        self.le_Diam.setObjectName("le_Diam")
        self.gridLayout.addWidget(self.le_Diam, 5, 1, 1, 1)
        self.le_FileName = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        self.le_FileName.setObjectName("le_FileName")
        self.gridLayout.addWidget(self.le_FileName, 0, 2, 1, 1)
        self.btn_OpenPipeNetworkFile = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        self.btn_OpenPipeNetworkFile.setObjectName("btn_OpenPipeNetworkFile")
        self.gridLayout.addWidget(self.btn_OpenPipeNetworkFile, 0, 0, 1, 2)
        self.le_EndNodeName = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_EndNodeName.sizePolicy().hasHeightForWidth())
        self.le_EndNodeName.setSizePolicy(sizePolicy)
        self.le_EndNodeName.setMinimumSize(QtCore.QSize(100, 0))
        self.le_EndNodeName.setObjectName("le_EndNodeName")
        self.gridLayout.addWidget(self.le_EndNodeName, 3, 1, 1, 1)
        self.btn_SamePipeNetworkFile = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        self.btn_SamePipeNetworkFile.setObjectName("btn_SamePipeNetworkFile")
        self.gridLayout.addWidget(self.btn_SamePipeNetworkFile, 1, 0, 1, 2)
        self.tree_Pipes = QtWidgets.QTreeWidget(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_Pipes.sizePolicy().hasHeightForWidth())
        self.tree_Pipes.setSizePolicy(sizePolicy)
        self.tree_Pipes.setMaximumSize(QtCore.QSize(50000, 50000))
        self.tree_Pipes.setMouseTracking(False)
        self.tree_Pipes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tree_Pipes.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tree_Pipes.setAllColumnsShowFocus(True)
        self.tree_Pipes.setWordWrap(False)
        self.tree_Pipes.setHeaderHidden(False)
        self.tree_Pipes.setObjectName("tree_Pipes")
        self.tree_Pipes.header().setMinimumSectionSize(35)
        self.gridLayout.addWidget(self.tree_Pipes, 1, 2, 7, 1)
        self.horizontalLayout.addWidget(self.grp_PipeAndNodeCreation)
        self.groupBox_4 = QtWidgets.QGroupBox(self.grp_PipeNetworkBuilder)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_AddPipeToLoop = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_AddPipeToLoop.setObjectName("btn_AddPipeToLoop")
        self.gridLayout_2.addWidget(self.btn_AddPipeToLoop, 1, 1, 1, 1)
        self.tree_Loops = QtWidgets.QTreeWidget(self.groupBox_4)
        self.tree_Loops.setObjectName("tree_Loops")
        self.tree_Loops.headerItem().setText(0, "Loops")
        self.gridLayout_2.addWidget(self.tree_Loops, 0, 3, 4, 1)
        self.le_LoopName = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_LoopName.sizePolicy().hasHeightForWidth())
        self.le_LoopName.setSizePolicy(sizePolicy)
        self.le_LoopName.setObjectName("le_LoopName")
        self.gridLayout_2.addWidget(self.le_LoopName, 0, 1, 1, 1)
        self.btn_CreateLoop = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_CreateLoop.setObjectName("btn_CreateLoop")
        self.gridLayout_2.addWidget(self.btn_CreateLoop, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 2, 1)
        self.tree_LoopPipes = QtWidgets.QTreeWidget(self.groupBox_4)
        self.tree_LoopPipes.setObjectName("tree_LoopPipes")
        self.gridLayout_2.addWidget(self.tree_LoopPipes, 0, 2, 4, 1)
        self.lbl_LoopName = QtWidgets.QLabel(self.groupBox_4)
        self.lbl_LoopName.setObjectName("lbl_LoopName")
        self.gridLayout_2.addWidget(self.lbl_LoopName, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.grp_PipeNetworkBuilder)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grid_Feedback = QtWidgets.QGridLayout()
        self.grid_Feedback.setObjectName("grid_Feedback")
        self.btn_Evaluate = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_Evaluate.setObjectName("btn_Evaluate")
        self.grid_Feedback.addWidget(self.btn_Evaluate, 0, 0, 1, 1)
        self.lbl_PipeHeadLosses = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_PipeHeadLosses.setObjectName("lbl_PipeHeadLosses")
        self.grid_Feedback.addWidget(self.lbl_PipeHeadLosses, 0, 2, 1, 1)
        self.lbl_NodePressures = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_NodePressures.setObjectName("lbl_NodePressures")
        self.grid_Feedback.addWidget(self.lbl_NodePressures, 0, 3, 1, 1)
        self.lbl_FlowRates = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_FlowRates.setObjectName("lbl_FlowRates")
        self.grid_Feedback.addWidget(self.lbl_FlowRates, 0, 1, 1, 1)
        self.lbl_PressureAndFlowChecks = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_PressureAndFlowChecks.setObjectName("lbl_PressureAndFlowChecks")
        self.grid_Feedback.addWidget(self.lbl_PressureAndFlowChecks, 0, 4, 1, 1)
        self.gridLayout_3.addLayout(self.grid_Feedback, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_StartNode, self.le_EndNodeName)
        Form.setTabOrder(self.le_EndNodeName, self.le_PipeLength)
        Form.setTabOrder(self.le_PipeLength, self.le_Diam)
        Form.setTabOrder(self.le_Diam, self.le_Roughness)
        Form.setTabOrder(self.le_Roughness, self.btn_AddPipe)
        Form.setTabOrder(self.btn_AddPipe, self.le_LoopName)
        Form.setTabOrder(self.le_LoopName, self.btn_AddPipeToLoop)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grp_PipeNetworkBuilder.setTitle(_translate("Form", "Pipe Network Builder"))
        self.grp_PipeAndNodeCreation.setTitle(_translate("Form", "Pipe and Node Creation"))
        self.lbl_EndNodeName_2.setText(_translate("Form", "Length (m)"))
        self.tree_Nodes.setSortingEnabled(True)
        self.tree_Nodes.headerItem().setText(0, _translate("Form", "Name"))
        self.tree_Nodes.headerItem().setText(1, _translate("Form", "External Flow"))
        self.tree_Nodes.headerItem().setText(2, _translate("Form", "Is Sprinkler"))
        self.tree_Nodes.headerItem().setText(3, _translate("Form", "Specified P/Min P"))
        self.lbl_EndNodeName.setText(_translate("Form", "Node 2"))
        self.le_StartNode.setText(_translate("Form", "a"))
        self.btn_DeletePipe.setText(_translate("Form", "Delete Pipe"))
        self.btn_AddPipe.setText(_translate("Form", "Add Pipe"))
        self.lbl_EndNodeName_4.setText(_translate("Form", "Roughness (m)"))
        self.le_PipeLength.setText(_translate("Form", "125"))
        self.le_Roughness.setText(_translate("Form", "0.00025"))
        self.lbl_EndNodeName_3.setText(_translate("Form", "Diam (mm)"))
        self.lbl_StartNode.setText(_translate("Form", "Node 1"))
        self.le_Diam.setText(_translate("Form", "300"))
        self.btn_OpenPipeNetworkFile.setText(_translate("Form", "Open Pipe Network File"))
        self.le_EndNodeName.setText(_translate("Form", "b"))
        self.btn_SamePipeNetworkFile.setText(_translate("Form", "Save Pipe Network File"))
        self.tree_Pipes.setSortingEnabled(True)
        self.tree_Pipes.headerItem().setText(0, _translate("Form", "Name"))
        self.tree_Pipes.headerItem().setText(1, _translate("Form", "Length (m)"))
        self.tree_Pipes.headerItem().setText(2, _translate("Form", "Diam (m)"))
        self.tree_Pipes.headerItem().setText(3, _translate("Form", "Rough (m)"))
        self.groupBox_4.setTitle(_translate("Form", "Loop Creation"))
        self.btn_AddPipeToLoop.setText(_translate("Form", "Add Pipe(s)"))
        self.btn_CreateLoop.setText(_translate("Form", "Create Loop"))
        self.tree_LoopPipes.headerItem().setText(0, _translate("Form", "Item"))
        self.tree_LoopPipes.headerItem().setText(1, _translate("Form", "Pipe Name"))
        self.lbl_LoopName.setText(_translate("Form", "Loop Name"))
        self.groupBox_2.setTitle(_translate("Form", "Output"))
        self.btn_Evaluate.setText(_translate("Form", "Evaluate Pipe Network"))
        self.lbl_PipeHeadLosses.setText(_translate("Form", "Pipe Head Losses"))
        self.lbl_NodePressures.setText(_translate("Form", "Node Pressures"))
        self.lbl_FlowRates.setText(_translate("Form", "Flow Rates"))
        self.lbl_PressureAndFlowChecks.setText(_translate("Form", "Pressure and Flow Checks"))

